<?php

namespace ContainerVFkiDsb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiExtensionDirectoriesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\API\ApiExtensionDirectoriesController' shared autowired service.
     *
     * @return \App\Controller\API\ApiExtensionDirectoriesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/API/ApiExtensionDirectoriesController.php';

        $container->services['App\\Controller\\API\\ApiExtensionDirectoriesController'] = $instance = new \App\Controller\API\ApiExtensionDirectoriesController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\API\\ApiExtensionDirectoriesController', $container));

        return $instance;
    }
}
