<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'api_extension_dirs' => [[], ['_controller' => 'App\\Controller\\API\\ApiExtensionController::directoriesChilds'], [], [['text', '/api/extension/get_dirs']], [], []],
    'api_extension_child_dirs' => [[], ['_controller' => 'App\\Controller\\API\\ApiExtensionController::returnHeader'], [], [['text', '/api/extension/header']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
    'directories_add' => [[], ['_controller' => 'App\\Controller\\DirectoriesController::addDirectory'], [], [['text', '/directories/add']], [], []],
    'memes_add' => [[], ['_controller' => 'App\\Controller\\DirectoriesController::addMeme'], [], [['text', '/meme/add']], [], []],
    'directories_rename' => [[], ['_controller' => 'App\\Controller\\DirectoriesController::renameDirOrImg'], [], [['text', '/directories/rename']], [], []],
    'delete_meme' => [[], ['_controller' => 'App\\Controller\\DirectoriesController::deleteMeme'], [], [['text', '/delete/meme']], [], []],
    'delete_dir' => [[], ['_controller' => 'App\\Controller\\DirectoriesController::deleteDirectory'], [], [['text', '/delete/dir']], [], []],
    'main' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
    'meme_panel' => [[], ['_controller' => 'App\\Controller\\MemePanelController::index'], [], [['text', '/meme']], [], []],
    'directory' => [['slug'], ['_controller' => 'App\\Controller\\MemePanelController::showDirectories'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/meme']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], []],
];
